"""
Hard Debias method implementation

This script performs:
1) Neutralization: remove gender-subspace projection from target neutral words.
2) Equalization: enforce symmetry for specified equalize pairs.

"""

from __future__ import annotations
import argparse
import json
import math
import os
from typing import Dict, List, Optional, Sequence, Set, Tuple
import numpy as np

from prepare_embedding import (
    EmbeddingHelper,
    read_definitional_pairs,
    read_word_list,
)

def load_subspace_components(report_path: str, k: int) -> np.ndarray:
    with open(report_path, "r", encoding="utf-8") as f:
        report = json.load(f)

    outputs = report.get("outputs", {})
    npy_path = outputs.get("gender_subspace_components_npy")
    if npy_path is None:
        raise ValueError(
            "Missing 'outputs.gender_subspace_components_npy' in "
            "gender_subspace_report.json. Use report generated by "
            "compute_gender_subspace.py."
        )
    if not os.path.isabs(npy_path):
        if os.path.exists(npy_path):
            pass
        else:
            # resolve relative to report directory.
            npy_path = os.path.join(os.path.dirname(report_path), npy_path)
    if not os.path.exists(npy_path):
        raise FileNotFoundError(f"Subspace .npy not found: {npy_path}")

    components = np.array(np.load(npy_path), dtype=np.float64)
    if components.ndim != 2 or components.shape[0] < 1:
        raise ValueError("Invalid components array in gender subspace report.")

    k_used = min(max(1, k), components.shape[0])
    raw = components[:k_used]  # [k, dim]

    # Re-orthonormalize for numerical stability.
    q, _ = np.linalg.qr(raw.T)  # [dim, k]
    return q[:, :k_used]

def project_to_subspace(v: np.ndarray, basis: np.ndarray) -> np.ndarray:
    # basis is [dim, k], with orthonormal columns.
    return basis @ (basis.T @ v)

def normalize(v: np.ndarray, eps: float = 1e-12) -> Optional[np.ndarray]:
    n = np.linalg.norm(v)
    if n < eps:
        return None
    return v / n

def equalize_pair(
    va: np.ndarray,
    vb: np.ndarray,
    basis: np.ndarray,
    eps: float = 1e-12,
    ) -> Tuple[Optional[np.ndarray], Optional[np.ndarray], Dict[str, float]]:
    """
    Equalize a pair so vectors are symmetric wrt gender subspace B while
    preserving their shared component orthogonal to B.

    For unit vectors:
      mu = (va + vb)/2
      mu_orth = mu - Proj_B(mu)
      y is a unit direction in B aligned with pair difference
      va' = normalize(mu_orth + radius * y)
      vb' = normalize(mu_orth - radius * y)

    This construction enforces symmetry in B and makes the pair equidistant
    to vectors with no B-component (gender-neutral in Hard Debias sense).
    """
    mu = (va + vb) / 2.0
    mu_orth = mu - project_to_subspace(mu, basis)
    mu_orth_norm_sq = float(np.dot(mu_orth, mu_orth))
    radius = math.sqrt(max(0.0, 1.0 - mu_orth_norm_sq))

    d = project_to_subspace(va - vb, basis)
    d_norm = float(np.linalg.norm(d))
    if d_norm < eps:
        # If pair difference has no stable B-direction, pick any basis axis.
        y_dir = basis[:, 0]
    else:
        y_dir = d / d_norm
    y = y_dir * radius

    va_new = normalize(mu_orth + y)
    vb_new = normalize(mu_orth - y)
    if va_new is None or vb_new is None:
        return None, None, {}

    # Method diagnostics:
    pa = project_to_subspace(va_new, basis)
    pb = project_to_subspace(vb_new, basis)
    metrics = {
        "symmetry_error_l2": float(np.linalg.norm(pa + pb)),
        "midpoint_orth_error_l2": float(np.linalg.norm(((va_new + vb_new) / 2.0) - mu_orth)),
    }
    return va_new, vb_new, metrics

def lookup_token_or_none(helper: EmbeddingHelper, word: str) -> Optional[str]:
    result = helper.lookup_token(word)
    if result.in_vocab and result.found_token is not None:
        return result.found_token
    return None

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--embedding_path", type=str, required=True)
    parser.add_argument(
        "--binary",
        action="store_true",
        help="Set for word2vec binary files (.bin/.bin.gz).",
    )
    parser.add_argument(
        "--gender_subspace_report",
        type=str,
        required=True,
        help="Path to gender_subspace_report.json containing components.",
    )
    parser.add_argument(
        "--target_words",
        type=str,
        required=True,
        help="Neutral target words to neutralize (one per line).",
    )
    parser.add_argument(
        "--gender_specific_words",
        type=str,
        default=None,
        help="Optional list of gender-specific words to exclude from neutralization.",
    )
    parser.add_argument(
        "--equalize_pairs",
        type=str,
        default=None,
        help="Optional equalize pairs file (same format as definitional pairs).",
    )
    parser.add_argument("--k", type=int, default=1, help="Subspace dimension (top-k PCs).")
    parser.add_argument("--output_dir", type=str, required=True)
    parser.add_argument(
        "--save_full_embedding_path",
        type=str,
        default=None,
        help="Optional path to save full debiased embedding in word2vec format.",
    )
    parser.add_argument(
        "--save_full_embedding_binary",
        action="store_true",
        help="If saving full embedding, save in binary format.",
    )
    return parser.parse_args()

def main() -> None:
    args = parse_args()
    os.makedirs(args.output_dir, exist_ok=True)

    if args.k <= 0:
        raise ValueError("--k must be >= 1")

    binary = (
        args.binary
        or args.embedding_path.endswith(".bin")
        or args.embedding_path.endswith(".bin.gz")
    )
    helper = EmbeddingHelper.load_word2vec(args.embedding_path, binary=binary)

    basis = load_subspace_components(args.gender_subspace_report, k=args.k)
    dim = helper.vector_size
    if basis.shape[0] != dim:
        raise ValueError(
            f"Dimension mismatch: subspace dim={basis.shape[0]} vs embedding dim={dim}"
        )

    target_words = read_word_list(args.target_words)
    gender_specific_words = (
        set(read_word_list(args.gender_specific_words))
        if args.gender_specific_words
        else set()
    )
    equalize_pairs = (
        read_definitional_pairs(args.equalize_pairs) if args.equalize_pairs else []
    )

    gender_specific_tokens: Set[str] = set()
    for w in gender_specific_words:
        tok = lookup_token_or_none(helper, w)
        if tok is not None:
            gender_specific_tokens.add(tok)

    modified: Dict[str, np.ndarray] = {}

    def current_vector(token: str) -> Optional[np.ndarray]:
        if token in modified:
            return modified[token]
        v = np.array(helper.kv[token], dtype=np.float64)
        return normalize(v)

    neutralization_rows = []
    neutralized_count = 0
    neutral_skipped_oov = 0
    neutral_skipped_gender_specific = 0
    neutral_skipped_zero = 0

    for w in target_words:
        tok = lookup_token_or_none(helper, w)
        if tok is None:
            neutral_skipped_oov += 1
            neutralization_rows.append(
                {"word": w, "status": "oov", "token": None}
            )
            continue
        if tok in gender_specific_tokens:
            neutral_skipped_gender_specific += 1
            neutralization_rows.append(
                {"word": w, "status": "gender_specific_skip", "token": tok}
            )
            continue

        v = current_vector(tok)
        if v is None:
            neutral_skipped_zero += 1
            neutralization_rows.append(
                {"word": w, "status": "zero_norm_skip", "token": tok}
            )
            continue

        v_deb = v - project_to_subspace(v, basis)
        v_deb = normalize(v_deb)
        if v_deb is None:
            neutral_skipped_zero += 1
            neutralization_rows.append(
                {"word": w, "status": "fully_in_subspace_skip", "token": tok}
            )
            continue

        modified[tok] = v_deb
        neutralized_count += 1
        neutralization_rows.append(
            {"word": w, "status": "neutralized", "token": tok}
        )

    equalize_rows = []
    equalized_pairs = 0
    equalize_skipped_oov = 0
    equalize_skipped_zero = 0

    for a, b in equalize_pairs:
        ta = lookup_token_or_none(helper, a)
        tb = lookup_token_or_none(helper, b)
        if ta is None or tb is None:
            equalize_skipped_oov += 1
            equalize_rows.append(
                {
                    "left_word": a,
                    "right_word": b,
                    "left_token": ta,
                    "right_token": tb,
                    "status": "oov_skip",
                }
            )
            continue

        va = current_vector(ta)
        vb = current_vector(tb)
        if va is None or vb is None:
            equalize_skipped_zero += 1
            equalize_rows.append(
                {
                    "left_word": a,
                    "right_word": b,
                    "left_token": ta,
                    "right_token": tb,
                    "status": "zero_norm_skip",
                }
            )
            continue

        va_new, vb_new, eq_metrics = equalize_pair(va, vb, basis)
        if va_new is None or vb_new is None:
            equalize_skipped_zero += 1
            equalize_rows.append(
                {
                    "left_word": a,
                    "right_word": b,
                    "left_token": ta,
                    "right_token": tb,
                    "status": "degenerate_skip",
                }
            )
            continue

        modified[ta] = va_new
        modified[tb] = vb_new
        equalized_pairs += 1
        equalize_rows.append(
            {
                "left_word": a,
                "right_word": b,
                "left_token": ta,
                "right_token": tb,
                "status": "equalized",
                "symmetry_error_l2": eq_metrics["symmetry_error_l2"],
                "midpoint_orth_error_l2": eq_metrics["midpoint_orth_error_l2"],
            }
        )

    # Save compact modified vectors artifact.
    modified_tokens = sorted(modified.keys())
    if modified_tokens:
        vectors = np.stack([modified[t] for t in modified_tokens], axis=0).astype(np.float32)
    else:
        vectors = np.zeros((0, dim), dtype=np.float32)

    vectors_npz_path = os.path.join(args.output_dir, "debiased_modified_vectors.npz")
    np.savez_compressed(
        vectors_npz_path,
        tokens=np.array(modified_tokens, dtype=object),
        vectors=vectors,
    )

    saved_full_embedding = None
    if args.save_full_embedding_path:
        for tok, vec in modified.items():
            helper.kv[tok] = vec.astype(np.float32)
        helper.kv.save_word2vec_format(
            args.save_full_embedding_path,
            binary=args.save_full_embedding_binary,
        )
        saved_full_embedding = args.save_full_embedding_path

    report = {
        "embedding_path": args.embedding_path,
        "gender_subspace_report": args.gender_subspace_report,
        "subspace_k": int(basis.shape[1]),
        "vector_dim": dim,
        "inputs": {
            "target_words_path": args.target_words,
            "gender_specific_words_path": args.gender_specific_words,
            "equalize_pairs_path": args.equalize_pairs,
        },
        "neutralization": {
            "total_target_words": len(target_words),
            "neutralized": neutralized_count,
            "skipped_oov": neutral_skipped_oov,
            "skipped_gender_specific": neutral_skipped_gender_specific,
            "skipped_zero_or_degenerate": neutral_skipped_zero,
            "rows": neutralization_rows,
        },
        "equalization": {
            "total_equalize_pairs": len(equalize_pairs),
            "equalized": equalized_pairs,
            "skipped_oov": equalize_skipped_oov,
            "skipped_zero_or_degenerate": equalize_skipped_zero,
            "rows": equalize_rows,
        },
        "outputs": {
            "modified_vectors_npz": vectors_npz_path,
            "modified_token_count": len(modified_tokens),
            "full_embedding_path": saved_full_embedding,
        },
        "notes": {
            "method": "Hard Debias (neutralize + equalize)",
            "neutralize": "Remove projection onto gender subspace for target neutral words.",
            "equalize": "Make pair members symmetric in gender subspace while keeping shared orthogonal component.",
        },
    }

    report_path = os.path.join(args.output_dir, "hard_debias_report.json")
    with open(report_path, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)

    print(f"[INFO] Neutralized words: {neutralized_count}/{len(target_words)}")
    print(f"[INFO] Equalized pairs: {equalized_pairs}/{len(equalize_pairs)}")
    print(f"[INFO] Modified tokens saved: {len(modified_tokens)}")
    print(f"[INFO] Saved modified vectors to: {vectors_npz_path}")
    print(f"[INFO] Saved report to: {report_path}")
    if saved_full_embedding:
        print(f"[INFO] Saved full debiased embedding to: {saved_full_embedding}")

if __name__ == "__main__":
    main()
